platform:ios,'8.0'


#target:Y2W_IM_SDK do
#    pod 'MQTTClient'
#end

target:yun2win do
    use_frameworks!

    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'DateTools'
    pod 'Realm', '~> 1.1.0'
    pod 'MBProgressHUD'
    pod 'IDMPhotoBrowser'
    pod 'JTSImageViewController'
    pod 'INTULocationManager'
    
    pod 'Bugrpt'
    pod 'UIViewController+Swizzled'
end
